FastLED/FastLED

pixeltypes.h
tl;dr Major new release of SmartMatrix is coming that isn't backwards compatible with the `SMART_MATRIX` controller, but still needs the CRGB-rgb24 conversion.  This minor change prevents conflicts.
We've been working on a major release for SmartMatrix that isn't going to be backwards compatible.  This is going to break the FastLED `SMART_MATRIX` controller, which I plan to fix and submit through a separate pull request after I lock down the major features for SmartMatrix 3.0.  In the meantime, I want to be sure that people who use FastLED functions can continue to do so with SmartMatrix 3.x.
New features in SmartMatrix 3.0 that may be relevant:
* New Layer class
* Default Foreground and Background Layers are separated and optional
* Custom layers (e.g. a Fadecandy Layer converting …
=> SmartMatrix 3.x Compatibility

led_sysdefs.h
[Simblee](https://www.simblee.com) seems identical to NRF51 and RFduino.
I've verified that this compiles, and a friend with the hardware has verified that it actually works, while I wait on my hardware to arrive.  Please let me know if you'd prefer this handled differently (or not at all).  :)
Thanks!
=> Added Simblee to led_sysdefs.h (same as NRF51 and RFduino).

FastLED.h
Was getting this compile error, tracked it down to a simple typo:
```
C:\Users\Jason\Documents\Arduino\libraries\FastLED/FastLED.h: In static member function 'static CLEDController& CFastLED::addLeds(CRGB*, int, int)':
C:\Users\Jason\Documents\Arduino\libraries\FastLED/FastLED.h:437:47: error: expected type-specifier before 'SixteenWayInlineBlockClocklessCOntroller'
case WS2813_PORTC: return addLeds(new SixteenWayInlineBlockClocklessCOntroller<NUM_LANES, NS(320), NS(320), NS(640), RGB_ORDER, 0, false, 300>(), data, nLedsOrOffset, nLedsIfOffset);
^
C:\Users\Jason\Documents\Arduino\libraries\FastLED/FastLED.h:437:152: error: expected primary-expression before ')' token
case WS2813_PORTC: return addLeds(new SixteenWayInlineBlockClocklessCOntroller<NUM_LANES, NS(320), NS(320), NS(640), …
```
=> Fixed compile error: FastLED.h:437:47: error: expected type-specifier before 'SixteenWayInlineBlockClocklessCOntroller'

pixeltypes.h
Allows the use of `const CRGB` objects and rvalue expressions as the first argument to *CRGB::lerp8* and *CRGB::lerp16*.
Consider the following example:
```
CRGB pixel;
CRGB red = CRGB::Red;
const CRGB red_const = red;
pixel.lerp8(red,       0); // OK
pixel.lerp8(-red,      0); // error: no known conversion for argument 1 from 'CRGB' to 'CRGB&'
pixel.lerp8(red_const, 0); // error: no known conversion for argument 1 from 'const CRGB' to 'CRGB&'
pixel.lerp8(CRGB::Red, 0); // error: no known conversion for argument 1 from 'CRGB::HTMLColorCode' to 'CRGB&'
```
The proposed change allows the latter three lines to compile and function as expected.
=> Make lerp8 and lerp16 reference parameters const

FastLED.h
error spotted by @unimatrix27 regrading the WS2813 problem broad up here #328
=> missing OCTOWS2813 in OWS2811 define

colorutils.h
Very simple patch which changes the counters used to scan the palette length from uint8_t to uint16_t.
This prevents a crash when palettes are larger than 255 bytes.  Granted they're still truncated down to 16 palette entries, but at least it isn't an infinite loop.
=> Fix for crash caused when loading large palettes (Issue #378)

platforms/esp/8266/clockless_block_esp8266.h
Moved showRGBInternal into iram cache, increased interrupt wait time to 10. This appears to work but interrupt timing may still require tuning.
=> Fixes ESP8266 parallel output

led_sysdefs.h, platforms.h, platforms/arm/k66/clockless_arm_k66.h, platforms/arm/k66/clockless_block_arm_k66.h, platforms/arm/k66/fastled_arm_k66.h, platforms/arm/k66/fastpin_arm_k66.h, platforms/arm/k66/fastspi_arm_k66.h, platforms/arm/k66/led_sysdefs_arm_k66.h
Add support for ARM MK66FX1M0 processor in Teensy 3.6.
Probably works for MK64FX512 in Teensy 3.5 (same pin layout and SPI capabilities)
Only tested with WS2811 led strip (+ 16-way parallel)
=> Teensy 3.6

pixelset.h
An implicit copy assignment operator is declared for CRGBArray, meaning we can't use the operator defined in the base class CPixelView.
A workaround is to use `operator()` to obtain a CPixelView:
```
CRGBArray<10> foo;
foo(0, foo.size()) = CRGB::White;
```
This fix allows us to use the CRGBArray directly:
```
CRGBArray<10> foo;
foo = CRGB::White;
```
=> Fix CRGBArray operator=

platforms/arm/kl26/clockless_arm_kl26.h
WS2812 on Teensy LC isn't adjusting the millis count when interrupts are disabled.
Here's a quick fix.  Conversation here:
https://plus.google.com/109760919253841662611/posts/LjcKxfxMKBb
=> Adjust millis on Teensy LC

platforms/esp/8266/clockless_block_esp8266.h
This extends the parallel output on the ESP8266 to a maximum of 6 channels by using GPIO4 and GPIO5 as channel 5 and 6.
The code is tested and works well on an ESP 8266-12.
=> Support 6-channel parallel output on ESP 8266

FastLED.cpp, lib8tion.h, platforms/avr/fastpin_avr.h
Adds support for ATtiny 841 and 441 controllers. I only have 841 hardware to test, but the 441 *should* be identical.
These controllers have hardware SPI, but the standard AVR SPI stuff didn't seem to work for me, so I've left it off for now.
=> Support ATtinyX41 boards.

fastled_delay.h, led_sysdefs.h, platforms.h, platforms/esp/32/clockless_block_esp32.h, platforms/esp/32/clockless_esp32.h, platforms/esp/32/fastled_esp32.h, platforms/esp/32/fastpin_esp32.h, platforms/esp/32/led_sysdefs_esp32.h
Credit to Rina Shkrabova for the first cut. Overall, this code is almost identical to the 8266 support, except for the pin definitions and the handling of interrupts. I put in calls to ets_intr_lock and ets_intr_unlock.
=> Support for ESP32

platforms/avr/fastpin_avr.h
Should be a fairly simple pull request as it's only one line. The ATmega328 (not p - picopower) is not currently included in the logic check with the others in the same series. I've added it so that the hardware pin map is correctly assigned and it does not revert to software mapping.
I had a project fail to compile when I had a ATmega328 part so I think this will help others.
John.
=> Add support for ATmega328 non-picopower hardware pins

FastLED.cpp, FastLED.h, colorutils.cpp, controller.h, fastpin.h, noise.cpp, pixelset.h, platforms/avr/led_sysdefs_avr.h, power_mgt.cpp
Also see https://github.com/FastLED/FastLED/issues/485
I've made very clean commits and everyone should be simple and understandable on its own. The inclusion of the additional headers is safe, as they are included by Arduino.h.
**All changes were tested with an  Arduino environment. The changed LED code for the power management also!**
* Less Arduino overhead (240 bytes for blink) with makefiles
* Better control with makefile environments
* Still Arduino compatible as before
=> Makefile Compilation Fix

platforms/avr/led_sysdefs_avr.h
Arduino's timer0_millis is called millis_timer_millis in ATTinyCore from Spence Konde (https://github.com/SpenceKonde/ATTinyCore)
I've compiled some example sketches to make sure nothing else looks broken
You have to use ATTinyCore 1.1.5 (or higher)  because of missing yield() export in previous versions
=> ATTinyCore support

platforms/arm/d21/clockless_arm_d21.h, platforms/arm/kl26/clockless_arm_kl26.h, platforms/arm/nrf51/clockless_arm_nrf51.h, platforms/avr/clockless_trinket.h
This change allows the library to be used outside of the standard libraries folders. An example of when this is useful is bundling the library with a sketch so that it can be distributed as a self-contained package.
Prior to this change compiling the library when not located in a standard libraries folder would fail with a "No such file or directory" error.
Fixes https://github.com/FastLED/FastLED/issues/569
=> Use relative paths for internal includes

platforms/esp/8266/clockless_block_esp8266.h, platforms/esp/8266/clockless_esp8266.h
WAIT_TIME set to 5 was too short and FastLED aborted frames too early
and restarted them incorrectly.
(as explained by Daniel Garcia in
https://plus.google.com/communities/109127054924227823508 )
Tested on ESP8266 with 768 LED matrix in both serialized output
and 3x 256 output.
=> WAIT_TIME=20 to allow interrupts without breaking matrix output.

platforms/arm/d21/fastpin_arm_d21.h
The [Gemma M0](https://www.adafruit.com/product/3501) has a Dotstar on pins 3 and 4. These aren't exposed via pads, however it's nice to be able to control it with FastLED, especially to chain it with the rest of the strands so it is included in light patterns (as it's a wearable platform).
This change adds pins 3 and 4 to the Gemma M0 definition and raises MAX_PIN to 4.
=> Allow control of the built in Dotstar on the Gemma M0

platforms/esp/32/clockless_esp32.h
Exit early if the interrupt is for another channel which is used by something else than FastLED.
This is needed if we use FASTLED_RMT_BUILTIN_DRIVER and lower FASTLED_RMT_MAX_CHANNELS in order to free some rmt channels for something else.
In this case doneOnChannel() is called for all rmt channels even if they don't belong to FastLED. So exit early in this case before the esp32 notices and reboots on its own.
=> only handle own rmt interrupts

keywords.txt
This adds the following keywords:
*  `CRGBArray`
*  `clearData`
*  `setMaxPowerInMilliWatts`
*  `setMaxPowerInVoltsAndMilliamps`
*  `setMaxRefreshRate`
This fixes #642.
=> Add some missing keywords for Arduino

FastLED.h
`str` macro conflicts with any function or method that has the same name ignoring namespaces and class names. Most noticeably it conflicts with `std::basic_stringstream::str()`. Using the standard library is possible on platforms like ESP32.
Secondly, there is no usage of the `str` macro in the library. A `grep -nr 'str(' .` gives:
```
./FastLED.h:7:#define xstr(s) str(s)
./FastLED.h:8:#define str(s) #s
./platforms/avr/clockless_trinket.h:271:// #define xstr(a) str(a)
./platforms/avr/clockless_trinket.h:272:// #define str(a) #a
./platforms/avr/clockless_trinket.h:273:// #define ADJDITHER2(D,E) asm __volatile__("subi %[" #D "], " xstr(DUSE) "\n\tand %[" #D "], %[" #E "]\n\t" ASM_VARS);
```
So there is a second, commented implementation for the avr platform, which is left untouched by this …
=> Remove str and xstr macros

led_sysdefs.h, platforms.h, platforms/arm/stm32/cm3_regs.h, platforms/arm/stm32/fastpin_arm_stm32.h, platforms/arm/stm32/led_sysdefs_arm_stm32.h
This mostly builds on previous work for SparkCore STM32103 (Cortex M3),
and patches from Evey Quirk @evq.
Unfortunately, stm32duino distribution does not include a header
with definitions for CoreDebug registers and flags etc.
so they were added to a newly created cm3_regs.h from
https://github.com/ARM-software/CMSIS/blob/master/CMSIS/Include/core_cm3.h
Tested on my Blue Pill, works fine
=> stm32duino port (Maple, Blue Pill etc.)

pixeltypes.h
=> Fixed Divide by 0 in CRGB::maximizeBrightness

platforms/arm/d21/fastpin_arm_d21.h
SAM D21 processor has single-cycle I/O port access available at PORT_IOBUS registers.  The PORT registers go through bus matrix and thus take a few extra cycles even under ideal conditions.  See section 23.5.10 - CPU Local Bus of SAM D21 [datasheet](http://ww1.microchip.com/downloads/en/DeviceDoc/SAMD21-Family-DataSheet-DS40001882D.pdf).
=> Change SAMD21 fastpin to use PORT_IOBUS instead of PORT

lib8tion.h
scale16 returns a uint16_t and it doesn't seem necessary to upcast.
=> Fix lerp16by16 where uint32_t should be uint16_t

platforms.h, platforms/arm/d21/fastpin_arm_d21.h, platforms/arm/d51/clockless_arm_d51.h, platforms/arm/d51/fastled_arm_d51.h, platforms/arm/d51/fastpin_arm_d51.h, platforms/arm/d51/led_sysdefs_arm_d51.h
Adds support for SAMD51 devices like the Adafruit M4 Express line.
I did see that support was added in 8f2e86434b2bfa4d6178622ca3745a68303f8b00 by assuming SAMD51 devices are the same as SAMD21, however in my experience this isn't the case. In fact I could not get FastLED to compile for the Adafruit Itsy-Bitsy M4 Express.
While this PR still mostly wholesale copies code from the D21 implementation (I noticed that D21 mostly wholesale copied from SAM, so hopefully this approach is ok) the critical difference is replacing `PORT_IOBUS` with `PORT` for fast pin access. `PORT_IOBUS` isn't defined by D51 devices (see another reference to this here: https://github.com/adafruit/Adafruit-GFX-Library/blob/master/Adafruit_SPITFT.cpp#L48)
With this patch I was able to compile and run the "Simple …
=> Enable SAMD51 (ARM Cortex M4) Support

platforms/arm/stm32/led_sysdefs_arm_stm32.h
This fixes the infamous
> (...)/FastLED/platforms/arm/stm32/led_sysdefs_arm_stm32.h:4:25:
>  fatal error: application.h: No such file or directory
issue when compiling code for Blue Pill (STM32F1xx).
The above `#include <application.h>` was initially added by
commit f149084 as part of the port for the particle photon
boards. While it's not entirely clear where this header
is coming from, it is clear that it's not there for the
usual Arduino + stm32duino.
So, to fix compilation for Blue Pill, while not breaking
it for particle photon, let's move the include to under
`#ifdef STM32F10X_MD`, the define which the original code
used.
Fixes: https://github.com/FastLED/FastLED/issues/741
=> stm32duino (Maple, Blue Pill, etc): compile fix

platforms/avr/fastpin_avr.h
The ATtiny25 does not have PORTA. It would give compilation errors.
Also, because the ATtiny25 has a very small storage capacity, a compilation message will be presented warning the user. (The library **will** (as of now) exceed the storage capacity on the ATtiny25)
=> Fix ATtiny25 compilation issue (port definitions)

platforms/arm/common/m0clockless.h, platforms/arm/d21/led_sysdefs_arm_d21.h
This adds support for FASTLED_ALLOW_INTERRUPTS to ARM M0-based platforms
(e.g. SAMD21).
This fixes the clock getting off when using more than ~30 LEDs, since
Arduino uses an interrupt to increment the millis clock.
This also fixes the breakage in NRF51 support introduced by dba882562703791ab909a7c4c4085f214e420444.
=> Re-enable interrupts in between writing LED data for ARM M0.

chipsets.h, fastspi.h, led_sysdefs.h, platforms.cpp, platforms.h, platforms/arm/nrf52/arbiter_nrf52.h, platforms/arm/nrf52/clockless_arm_nrf52.h, platforms/arm/nrf52/fastled_arm_nrf52.h, platforms/arm/nrf52/fastpin_arm_nrf52.h, platforms/arm/nrf52/fastpin_arm_nrf52_variants.h, platforms/arm/nrf52/fastspi_arm_nrf52.h, platforms/arm/nrf52/led_sysdefs_arm_nrf52.h
This has FastPIN, FastSPI, and clockless.
LED strings for clockless are temporarily limited to 144 LEDs,
adjustable via led_sysdefs.h #define to any length needed,
limited only by RAM..
=> Enable support for nRF52 chipset.

platforms/arm/nrf52/fastpin_arm_nrf52.h
Fix #842
Specifically, cannot cast integer values to pointers in a constexpr,
requiring use of intptr_t in the constexpr.  Callers of the constexpr
may then cast it at the non-constexpr location of use.
See https://stackoverflow.com/questions/10369606/constexpr-pointer-value
=> Fix #842 by increasing compliance with constexpr restrictions

platforms/arm/nrf52/clockless_arm_nrf52.h
Avoid first-time pin initialization from affecting showLeds() for clockless chipsets.
Fixes #856.
If a sketch does not initialize pins to low state (or high when _FLIP=1), 
the first call to showLeds() may intialize pin state, which clockless LEDs
may treat as part of a data stream.
Avoid this by also initializing the pin state in Init(), and
call mWait.mark() to ensure LEDs will not consider this part of the
LED data.
=> NRF52 -- Prevent pin initialization affecting clockless LED data

platforms/arm/nrf52/clockless_arm_nrf52.h
Fixes #840.
<details>
<summary>A textbook case of where `volatile` is necessary</summary>
<p>
The variable `s_SequenceBufferInUse` is modified in an ISR.
However, the variable was **_not_** marked `volatile`:
```C++
virtual void showPixels(PixelController<_RGB_ORDER> & pixels) {
while (s_SequenceBufferInUse != 0);
```
Because it wasn't marked `volatile`, the compiler was allowed to use the first value it read.  Using [compiler explorer](https://gcc.godbolt.org/) set to `ARM gcc 7.2.1 (none)` with optimizations (e.g., `-O5`), you would get something similar to:
```asm
.L10
.word .LANCHOR0 // address of .LC0
.word .LC0             // s_SequenceBufferInUse
showPixels():
ldr     r3, .L10
ldr     r3, [r3]
cmp     r3, #0
beq     .L6
.L7:
b       .L7 // Note this doesn't re-read the value..... …
```
=> Fix nRF52 race condition / hard lock

platforms/arm/nrf52/fastpin_arm_nrf52.h
This was causing it to not compile on the Adafruit Feather nRF52840 Express for me.
This should fix this issue: https://github.com/FastLED/FastLED/issues/938
=> Underscore was missing

platforms/avr/fastpin_avr.h
The `atmega16` has the same pinout at the `atmega32` when using the MightyCore board
in arduino.
The pinout according to the Mightcore documentation can be seen here:
This commit just adds `__AVR_ATmega16__` to the macro in `fastpin_avr.h` so it builds with the atmega16 target.
It seems like this should be a safe change, but I'm not 100% sure this is how it should be done.  However, I tested this on my Atmega16 board, and appears to work like a charm so I figured it was worth tossing a PR out incase it can help other people :)
Signed-off-by: Charlie Mooney <cmooney3@gmail.com>
=> Add Atmega16 support to fastpin_avr.h (Mightycore Arduino)

platforms/arm/d21/fastpin_arm_d21.h
The pins here were based on an early draft of the Nano 33 IOT package where the pin definitions were mislabeled in the comments - https://github.com/arduino/ArduinoCore-samd/blob/08629f90b1f803017cc526c4cbbe3eaaccc8f062/variants/nano_33_iot/variant.cpp
This has recently been fixed - 
https://github.com/arduino/ArduinoCore-samd/blob/master/variants/nano_33_iot/variant.cpp
This change uses the correct pin definitions.
I chose to use the last SPI, but we might want to change that to something else, as it's used by the WiFi module and I'm not exactly sure what FastLED plans to use it for, but we may run into conflicts.
=> Fix Nano 33 IOT pindef

pixelset.h
… data
In the operator implementation the `leds` pointer is already shifted to the opposite end of the data. Using the constructor with start and end index however does the shift again. A simple fix would be the shift in the operator.
=> CPixelView operator-() result points to wrong data

platforms/arm/mxrt1062/fastled_arm_mxrt1062.h
Recently there was reported that the WS2812Serial library (github.com/PaulStoffregen/WS2812Serial) was not ported over to work on the new Teensy T4, so I thought I would take a look.
I added the T4 support, which is now pending in a Pull Request.  During that I also found that there were errors in one of the core header files for the T4, which I also fixed, which is now pending in another Pull Request (github.com/PaulStoffregen/Cores)
After that was working, it was pointed out that the FastLED sample in the WS2812Serial librry did not compile. So...
More details in the forum Thread:
https://forum.pjrc.com/threads/58442-Non-Blocking-WS2812-LED-Library-and-Teensy-4-0
Note: I simply added the three include files from the ../k20 directory in the same way that was done for the T3.5 and T3.6
=> Support WS2812Serial Library on Teensy T4

FastLED.h
The SPI_DATA_RATE template parameter to addLeds() is declared as a uint8_t. On Teensy 4, DATA_RATE_MHZ and DATA_RATE_KHZ are defined to pass the raw clock rate in Hz to the Controller class, yielding values larger than 255. The value is truncated resulting in an incorrect/unusable SPI clock rate. I fixed this by redefining as uint32_t.
=> Fix truncated SPI_DATA_RATE template parameter to addLeds with Teensy 4

library.properties
re: [ardiono library spec](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification)
add ```includes``` section to the arduino ```library.properties``` file to allow the arduino IDE to only include the specified include (arduino IDE >v1.6.10) 
instead of every ```.h``` file found in the root dir of the library
=> add include for arduino library 

platforms/arm/nrf52/fastpin_arm_nrf52.h
nrf52832, nrf52810, and nrf52811 have a single GPIO port, and do not define NRF_P1_BASE.  If NRF_P1_BASE is not defined, do not define the generated structures requried to access GPIO port 1.
=> Fix compilation for NRF52 chips with a single GPIO port such as NRF52832

platforms/esp/32/clockless_rmt_esp32.h
(1) A forced minimum delay of 50 microseconds between calls to show(). The way the driver is written it does not explicitly send a latching signal. I noticed that on the ESP32 it is possible to call show() so quickly that the strip doesn't latch, and the new signal appears to be an extension of the previous one.
(2) An option to lock out SPI flash access (e.g., using SPIFFS) during a call to show(). SPI flash access on the ESP32 requires a lockdown of the memory bus. To enforce this requirement, the ESP-IDF system software disables all tasks on *both* cores until flash operations complete. If this lockout happens during a call to show(), the timing gets off, and the LEDs look flashy. I added a switch that causes the driver to acquire a lock on the flash system, effectively delaying the …
=> Better timing stability for ESP32

pixeltypes.h
RGB values in CRGB structs can be accessed through the array subscript operator but the values in CHSV structs can not.
=> Overload array subscript operator for CHSV structs

lib8tion/random8.h
Since many popular low-cost chipsets do not have a native multiply operation,
this calculation can be executed much more efficiently using only add and left shift.
=> Convert rand multiplication constants to shifts and adds.

platforms/avr/clockless_trinket.h
fixes clockless_trinket.h:326:24: error: expected primary-expression before '__attribute__' on older gcc versions
=> fix for older gcc versions

platforms/esp/32/clockless_i2s_esp32.h, platforms/esp/32/clockless_rmt_esp32.h
Fixes RMT hang mentioned in #835
=> ESP32: Fixed SemaphoreGive when using RMT builtin driver

platforms/arm/d21/fastpin_arm_d21.h
This PR adds support to FastLED for the Seeeduino XIAO Cortex-M0+ board [(http://wiki.seeedstudio.com/Seeeduino-XIAO/).](http://wiki.seeedstudio.com/Seeeduino-XIAO/).  
The mapping was derived from [https://github.com/Seeed-Studio/ArduinoCore-samd/blob/master/variants/XIAO_m0/variant.cpp](https://github.com/Seeed-Studio/ArduinoCore-samd/blob/master/variants/XIAO_m0/variant.cpp), and I verified these changes on one of my XIAO boards.
Thanks!
=> add platform support for the Seeeduino XIAO board

platforms/esp/32/clockless_rmt_esp32.h
It took me a second to realize there needs to be a value for this define or compilation fails. I've updated the comment to clarify this for future visitors.
=> Clarify instructions for FASTLED_RMT_BUILTIN_DRIVER

platforms/arm/mxrt1062/block_clockless_arm_mxrt1062.h, platforms/arm/mxrt1062/clockless_arm_mxrt1062.h
=> Ensure getMaxRefreshRate() returns a non-zero default for Teensy 4.x

platforms/arm/nrf52/fastpin_arm_nrf52_variants.h, platforms/arm/nrf52/led_sysdefs_arm_nrf52.h
This adds the necessary pin definitions for this board.
All pins were toggled using FastPin<>::toggle().
Thanks to @ardnew for pointing out an early error!
Supported pins:
*  ~~A0 / D12 / AUDIO OUT~~ == connected to on-board audio amplifier, not sure if can output clean signal? 
Manual [test sketch](https://gist.github.com/henrygab/1d4825a72864908e0204c3e18d6ba539) used to verify correct pins is available.
Fixes #978 
Also fixes #1023
=> Enable Circuit playground Bluefruit

chipsets.h
Fixes PIXIE and the PixieController being undefined for newer versions of [espsoftwareserial](https://github.com/plerup/espsoftwareserial) because of the different symbol defined for inclusion.
```
#if defined(SoftwareSerial_h) || defined(__SoftwareSerial_h)
```
should get both versions.
[SoftwareSerial.h](https://github.com/plerup/espsoftwareserial/blob/91ea6b1b1c34601565b23c96c4441f2d399a4f99/src/SoftwareSerial.h#L25)
=> fix for newer SoftwareSerial.h using differently named macro for inclusion

pixeltypes.h
fix for class-memaccess warnings for the `CRGB` and `CHSV` structs.
fixes the same warnings as #986 (discussion #985) and #977 (discussion #971)(which are duplicates), except that this removes the warning from all uses that require `CRGB` and `CHSV` to be trivially copyable.
As littlebalckfish [said](https://github.com/FastLED/FastLED/issues/971#issuecomment-591734979)
<details><summary>Quote</summary>
> memmove signature from stdlib is
> 
> `void * memmove ( void * destination, const void * source, size_t num );`
> 
> So, casting all the pointers to (void*), I believe, is an appropriate, if not optimal solution to the problem, i.e.
> 
> `memmove8( &(entries[0]), &(rhs.entries[0]), sizeof( entries));`
> 
> to
> 
> `memmove8( (void *) &(entries[0]), (void *) &(rhs.entries[0]), sizeof( …
=> use default copy constructor and copy assignments for CRGB and CHSV

platforms/esp/32/clockless_rmt_esp32.h
Deleted unused variables.
```
In file included from C:\Users\tanaka\Documents\Arduino\libraries\FastLED-master/platforms/esp/32/fastled_esp32.h:8:0,
from C:\Users\tanaka\Documents\Arduino\libraries\FastLED-master/platforms.h:36,
from C:\Users\tanaka\Documents\Arduino\libraries\FastLED-master/FastLED.h:52,
from sketch\M5LiteLED.h:5,
from sketch\M5Lite.h:30,
from C:\Users\tanaka\Documents\Arduino\_M5Lite\_M5Lite.ino:2:
C:\Users\tanaka\Documents\Arduino\libraries\FastLED-master/platforms/esp/32/clockless_rmt_esp32.h: In instantiation of 'void ClocklessController<DATA_PIN, T1, T2, T3, RGB_ORDER, XTRA0, FLIP, WAIT_TIME>::fillNext() [with int DATA_PIN = 27; int T1 = 60; int T2 = 150; int T3 = 90; EOrder RGB_ORDER = (EOrder)66u; int XTRA0 = 0; bool FLIP = false; int WAIT_TIME = 5]': …
```
=> Fix unused variable t1

platforms/avr/fastpin_avr.h
FastLED already supports the ATMega1284P, but I happen to only have plain ATMega1284 parts in my geekroom.
The only difference between an ATMega1284P and a regular ATMega1284 is that the P is the picopower version that uses less power, so all one needs to do is add one more define and it works just fine.
=> Add support for non-P ATMega1284 device

chipsets.h, platforms/avr/clockless_trinket.h
As more and more Arduino nano/pro clones with LGT8F328-chips show up, they should get supported.
It's some more updated version of the Atmega328, so many ops have lower cycle count. This PR adds support for the current timing up to max (32MHz) chip speed.
=> added support for LGT8F arduino nano and pro clones

examples/XYMatrix/XYMatrix.ino
In the XYMatrix example one now may chose whether the matrix is placed vertically by rotating it 90 degrees clockwise with the  boolean kMatrixVertical option.
=> implemented the option to place the matrix vertically

led_sysdefs.h, platforms/avr/clockless_trinket.h, platforms/avr/fastpin_avr.h, platforms/avr/led_sysdefs_avr.h
The changes in PR is expecting no other behavioural changes, except on the support to ATmega4809 platform.
Changes was ported over in the zipfile in threads in https://github.com/FastLED/FastLED/issues/716, with some minimal changes detailed in the commit messages.
Pushing this forward as the changes is minimal, although I'm aware of the other working branch `avrmega` that commits are behind master. We can probably do the improvements (eg. refactoring/organizations of files) over there. Suggesting rebase master in the branch when possible. Related thread for work-in-progress on the same platform: https://github.com/FastLED/FastLED/issues/858.
=> Support on ATmega4809 with minimal changes

platforms/esp/8266/fastpin_esp8266.h
Fix #1103 
Tested with 2 ESP8266 boards and 2 WS2811 LEDs - more details in the issue above.
=> Fix FastPin GPIO16 on ESP8266!

component.mk
I found, when updating FastLED to the latest `src` directory change, that I was getting a lot of errors about missing files!
I think this is due to the new `src` directory, which I think is a very good idea and cleans up the repository a lot. Seems as though `component.mk`'s list of paths is not searched recursively for files.
I also had to add `src/platforms/esp32` to the paths for the new clockless files to be found, otherwise I had a lot of these errors in the linker:
```
libmain.a(main.o):(.literal._ZN15SoulmateLibrary15lightPercentageEf[SoulmateLibrary::lightPercentage(float)]+0xc): undefined reference to `FastLED'
libmain.a(main.o):(.literal._ZN15SoulmateLibrary15lightPercentageEf[SoulmateLibrary::lightPercentage(float)]+0x10): undefined reference to `fill_solid(CRGB*, int, CRGB …
```
=> Update component.mk to work with ESP-IDF 3.3.x

src/platforms/esp/32/clockless_rmt_esp32.cpp
These changes should ensure that all code needed to push the bits out during FastLED.show() are in IRAM. Some of the ESP-IDF function we rely on do not have the IRAM_ATTR, so if they are executed during a flash memory operation, the program fails. The solution is to inline the code (basically, direct access to RMT registers) into our functions, which do have the IRAM attribute.
=> Inline RMT functions needed to get code in IRAM

src/platforms/esp/32/clockless_rmt_esp32.cpp, src/platforms/esp/32/clockless_rmt_esp32.h
The RMT init code only needs to be invoked one time, the first time show() is called, so I chose pin 0 as a stand-in for whatever pins would be used later. Unfortunately, the rmt_config code does configure the pin, so choosing pin 0 is not benign. Instead, I just pass in one of the pins that will actually be used (it doesn't matter which one).
In the long run I'd like to change the setup code to avoid this problem altogether.
=> Fix for issue #1130: don't use pin 0 to configure the RMT device

src/lib8tion/trig8.h
code optimized for AVR platform containing AVR assembly should only be included when compiling for AVR. 
Reason for change: I was experimenting to compile for a new platform, and got compilation errors.
=> include optimized sin/cos code for AVR only when on this platform

.github/workflows/build.yml, README.md, ci/ci-compile, examples/Cylon/Cylon.ino, examples/Multiple/ArrayOfLedArrays/ArrayOfLedArrays.ino, examples/Multiple/MultipleStripsInOneArray/MultipleStripsInOneArray.ino, examples/Noise/Noise.ino, examples/NoisePlayground/NoisePlayground.ino, examples/RGBSetDemo/RGBSetDemo.ino
Reason for Request: make sure code compiles when new PR's are submitted. This PR could later be used as a base for adding host-based unit tests for e.g. platform-independent code.
The examples are built for various different boards/platforms. Where necessary, examples were slightly changed to enable compilation also for ESP8266 and ESP32 platforms (to pass `static_asserts` checking for certain pin's).
The script `ci/ci-compile` performs the build and is run during a Github Actions workflow. The script can also be run locally.
See https://github.com/jandelgado/FastLED/actions/runs/445634210 for an example
=> Build examples in CI using Github Actions

src/platforms/esp/32/clockless_rmt_esp32.cpp, src/platforms/esp/32/clockless_rmt_esp32.h
These changes fix a bug related to the management of the number of RMT channels used (and the number of RMT memory blocks used). There were two problems: 
(1) The preprocessor values FASTLED_RMT_MAX_CHANNELS and FASTLED_RMT_MEM_BLOCKS were not configurable from within a sketch because the code for the driver is now in a separate cpp file, which is not compiled with the sketch file.
(2) FASTLED_RMT_MAX_CHANNELS was being incorrectly computed as a function of FASTLED_RMT_MEM_BLOCKS, which is not right. The max channel should be independent of the number of memory blocks.
This PR also includes a change to the code that copies the pixel data to make it faster.
=> Fix for a bug that was limiting parallelism

src/platforms/avr/fastpin_avr.h, src/platforms/avr/fastspi_avr.h
Tested working with official Arduino Nano Every and an APA102 LED strip.
The Arduino Nano Every pinout sheet (https://content.arduino.cc/assets/Pinout-NANOevery_latest.pdf),  lists the SPI0 ports in the ALT2 portmux position (PE[3:0]), so that's where they're set in this PR using the PORTMUX_TWISPIROUTEA register (page 138 in http://ww1.microchip.com/downloads/en/DeviceDoc/ATmega4808-4809-Data-Sheet-DS40002173A.pdf). This could be configurable with some more effort.
=> Add hardware SPI support for Arduino Nano Every

src/platforms/esp/32/clockless_i2s_esp32.h, src/platforms/esp/32/clockless_rmt_esp32.h
=> Fix deprecated warnings about #include "esp_intr.h"

src/platforms/arm/d51/fastpin_arm_d51.h
Pulled the definitions from the [variants](https://github.com/adafruit/ArduinoCore-samd/blob/master/variants/matrixportal_m4/variant.cpp) file. Tested working (for pin 4/`PIN_NEOPIXEL`, at least). For SPI I chose the secondary SPI port, since the first is in use by the ESP32 coprocessor. It's rather academic as neither of the SPI ports are broken out to the board.
As one of the pins is bit 31, I needed to [change the definition](https://github.com/FastLED/FastLED/compare/master...Hevi-dev:matrixportal-m4?expand=1#diff-f18dce76c03225559d8bfb64c2b8ac4ce0aea030652e04f39599fb4a889f731eR62) of the macro to unisgned long. I hopefully did so in a manner that is compatible with other boards/compilers.
=> Add support for Adafruit MatrixPortal M4

src/platforms/esp/32/clockless_rmt_esp32.cpp, src/platforms/esp/32/clockless_rmt_esp32.h
ESP32S2 has only 4 channels in the RMT peripheral compared to the 8 channels in ESP32. Some interrupt bits need to fixed to ensure it works properly on both platforms.
Sanity tested this fix on both ESP32 and ESP32S2.
I'm not sure this is the best way to test for S2 vs. vanilla - happy to change it if anyone suggests a better option
=> Fixed ESP32 clockless RMT to work on ESP32S2

src/led_sysdefs.h, src/platforms.h, src/platforms/arm/stm32/clockless_arm_stm32.h, src/platforms/arm/stm32/fastpin_arm_stm32.h, src/platforms/arm/stm32/led_sysdefs_arm_stm32.h
Pinout and other changes upstreamed from
https://github.com/focalintent/FastLED-Sparkcore/blob/master/firmware/fastpin_arm_stm32.h
As that repository is 5 years old.
---
A few other steps are needed to actually compile using particle compiler because of how it flattens the directory structure[1]
Afterwards I can build both with the particle compiler and local toolchain.
```
cd src
sed -i 's!#include "lib8tion/!#include "!' lib8tion.h
sed -i 's!platforms/arm/stm32/!!' src/led_sysdefs.h platforms.h
for fn in `ls lib8tion/* platforms/arm/stm32/*`; do echo "ln -s $fn $(basename $fn)"; done
git checkout pixelset.h pixeltypes.h
sed -i -E 's! ::(scale8|fill_rainbow|fill_gradient|napplyGamma_video|nblend|blur1d)! NSFastLED::\1!' pixeltypes.h pixelset.h
sed -i -E 's! …
```
=> Add Particle Photon(STM32F2XX) support

examples/Cylon/Cylon.ino, examples/DemoReel100/DemoReel100.ino, examples/Fire2012/Fire2012.ino, examples/Fire2012WithPalette/Fire2012WithPalette.ino, examples/Multiple/OctoWS2811Demo/OctoWS2811Demo.ino, examples/Multiple/ParallelOutputDemo/ParallelOutputDemo.ino, examples/Noise/Noise.ino, examples/NoisePlayground/NoisePlayground.ino, examples/NoisePlusPalette/NoisePlusPalette.ino, examples/SmartMatrix/SmartMatrix.ino, examples/TwinkleFox/TwinkleFox.ino, examples/XYMatrix/XYMatrix.ino
As suggested in #1208 this updates:
LEDS.[function] to FastLED.[function]
Switch from byte to uint8_t
Use uint16_t for all LED index variables
Remove messages about minimum version
=> Some Modernization updates for #1208

src/platforms/esp/32/clockless_rmt_esp32.cpp, src/platforms/esp/32/clockless_rmt_esp32.h
This fixes issue #1229 
The strategy is just to look at the size of the LEDs array at each call to show and make sure we adjust the size of the buffer to accommodate it. To avoid lots of dynamic memory allocation, we only grow the buffer -- a request for a smaller array of LEDs will just use a fraction of the buffer.
=> Fix for ESP32 driver not properly handling setLeds

src/platforms/arm/mxrt1062/block_clockless_arm_mxrt1062.h
issue #1224
Declared MS_COUNTER and initialized to 0.
previously undefined when using with teensy 4.1
=> Defined MS_COUNTER

src/platforms/esp/32/clockless_i2s_esp32.h
A simple change to check for a set `FAST_INTERNAL` define to suppress the _"NOTE: ESP32 support using I2S parallel driver. All strips must use the same chipset"_ message from the ESP32 I2S driver if you know what you're doing and want to clean up your compile output a bit :wink:
=> Use FASTLED_INTERNAL define to suppress pragma message from the ESP32 I2S driver

src/pixeltypes.h
http://fastled.io/docs/3.1/struct_c_r_g_b.html
`nscale8` accepts both `uint8_t scaledown` and `const CRGB & scaledown` while `scale8` only accepts `const CRGB & scaledown`
If anyone is currently passing a `uint32_t` or `uint8_t` it gets cast to a CRGB, which causes the R and G channel to be zerod and scales only the blue channel. This will be a behavior "change" but IMHO it's a fix.
=> Add scale8(uint8)

src/pixeltypes.h
The unary minus operator of `CRGB` returns a new `CRGB` object and should therefore be `const`. In fact, this is a bug. Having a function like the following cannot call the unary minus.
```c++
CRGB complement(CRGB const& color) {
return -color; // yields CRGB(255, 255, 255)
}
```
Adding a `const` qualifier should resolve the issue.
=> Add missing const in unary operator-

examples/NoisePlusPalette/NoisePlusPalette.ino, src/noise.h
Simplex noise is something different and is not implemented by the FastLED library (yet!). Therefore, don't confuse people by calling it Simplex Noise.
It appears there are 3 variants of noise developed by Ken Perlin:
- Classical Perlin noise.
- An "improved" noise - AFAIK just small improvements over classical Perlin noise.
- Simplex Noise. This algorithm is a bit more complicated and works in a different way. It allows noise up to many dimensions without too much computational overhead: O(n+1) instead of O(2^n). It also has fewer artifacts, that are sometimes quite visible in classical/improved noise. Downside: it's patented until early 2022.
I've looked at the noise.cpp file and it looks a lot more like the improved noise (https://mrl.cs.nyu.edu/~perlin/noise/) than simplex noise …
=> Fix incorrectly calling perlin noise "Simplex Noise"

src/platforms/esp/32/clockless_rmt_esp32.cpp, src/platforms/esp/32/clockless_rmt_esp32.h
The flags field was not initialized to 0 (No flags) which caused
random failures of the esp32 RMT driver (Depending on what
was in the unitialized memory).
Also added support for debugging output in ESP32 RMT Driver
(Disabled by default).
related: https://github.com/FastLED/FastLED/issues/1300
=> esp32: Fix unitialized flags field in init of the RMT driver

src/platforms/arm/mxrt1062/clockless_arm_mxrt1062.h, src/platforms/arm/mxrt1062/fastled_arm_mxrt1062.h, src/platforms/arm/mxrt1062/octows2811_controller.h
Fixes multiple timing issues with Teensy 4.0 & 4.1.
Issue first reported on this forum thread:
https://forum.pjrc.com/threads/68437-FastLED-SK6805-Teensy-4-1-and-a-Teensy-rookie-full-white-only
=> Fix WS2812B timing on Teensy 4.x

src/platforms/esp/32/led_sysdefs_esp32.h
Improve compatibily with older versions of ESP32 Arduino core.  Tested with versions 1.0 & higher.
=> Improve compatibility with older ESP32 Arduino core versions

src/lib8tion/math8.h
The SCALE8_FIXED version of blend8 uses the formula
```
result = (A*(255-amountOfB) + A + B*amountOfB + B) >> 8
```
The current implementation takes 11 cycles on AVR, and requires 2 multiplications on all platforms.
However, by rearranging this to
```
result = (256*A + B - A*amountOfB + B*amountOfB) >> 8
```
We can save 4 or 5 cycles (depending on how the optimiser sets up a and b inputs for that extra cycle)
We can rearrange further to 
```
result = (256*A + B + (B-A)*amountOfB) >> 8
```
…and this seems to compile down to fewer instructions and reduce it to only 1 multiplication on other platforms.
=> Improve the speed of blend8 on AVR by 20-30%, and on other platforms by some amount

src/platforms/avr/clockless_trinket.h
Without this patch, a 0 length pixel array is treated as if it's 65535 long. Whilst few people will encounter this bug in simple applications, it comes up frequently when manipulating ranges of pixels with multiple PixelControllers.
=> Prevent FastLED from hanging on 0-length pixel arrays

src/platforms/avr/clockless_trinket.h
Daniel Garcia commented out all of the other code which goes with this block in b9b23091 (2015). Remove this last remnant.
=> Remove clobbering of TCCR0A left over from ancient times

src/fastled_delay.h
You may want this if you are doing your own frame-rate accounting and don't want to waste cycles waiting for FastLED between frames.
You may also want this if you are intentionally calling show() multiple times for the same strip.
=> Make the minimum wait optional by defining NO_MINIMUM_WAIT

src/platforms/esp/32/clockless_rmt_esp32.h
Otherwise `errcode` is considered set but unused when not in DEBUG.
=> Prevent -Wunused-but-set-variable in clockless_rmt_esp32.h

ci/ci-compile, ci/ci-flags.py
Reduces so many warnings about `-Wregister`
```
$ pio ci --board=esp01 --lib src "examples/Blink/" |& grep -o '\[\-W.*\]' | sort | uniq -c | sort -n
2 [-Wdeprecated-declarations]
9 [-Wmisleading-indentation]
632 [-Wregister]
$ PLATFORMIO_BUILD_FLAGS="-Wno-register" pio ci --board=esp01  --lib src "examples/Blink/" |& grep -o '\[\-W.*\]' | sort | uniq -c | sort -n
2 [-Wdeprecated-declarations]
9 [-Wmisleading-indentation]
```
Locally this removes 11382 of 11658 total warnings during ci/ci-compile
My other pull request has 54,353 lines in CI check. This PR reduces that to 13,866!
---
You can get 95% of the way here with 
`$ PLATFORMIO_BUILD_FLAGS="-Wno-register" pio ci --board=esp01  --lib src "examples/Blink/"`
But you'll get a few extra warnings about
`cc1: warning: command-line option …
=> Remove -Wregister warnings during CI

src/lib8tion.h, src/lib8tion/math8.h
* `qadd7()` behaved differently when compiled for different platforms
* `avg7()` and `avg15()` gave wrong results when their C versions were compiled
* `qmul8()` had an extra instruction
* Unused register was clobbered in `ease8InOutApprox()`
* Added `avg8r()` and `avg16r()`, they round the result up
#295 tried to fix `qadd7()`
=> Fix some math8 functions, improve qmul8(), minor extensions, fix typos

keywords.txt, src/colorutils.cpp, src/colorutils.h
This adds a utility function (`fill_rainbow_endless`) for filling a complete rainbow pattern onto a strip so that it's continuous in hue between the end of the strip and the beginning. Useful for out-of-the-box rainbow animations on looped strips and LED rings.
```cpp
void loop() {
static uint8_t hue = 0;
EVERY_N_MILLIS(2) { hue++; }
fill_rainbow_endless(leds, NUM_LEDS, hue);
FastLED.show();
}
```
https://user-images.githubusercontent.com/24282108/129810065-a7c7325e-2ba4-42af-b8a5-01132f9e012f.mp4
=> Create fill_rainbow_circular and fill_palette_circular functions

src/led_sysdefs.h, src/platforms.h, src/platforms/arm/rp2040/clockless_arm_rp2040.h, src/platforms/arm/rp2040/fastled_arm_rp2040.h, src/platforms/arm/rp2040/fastpin_arm_rp2040.h, src/platforms/arm/rp2040/led_sysdefs_arm_rp2040.h, src/platforms/arm/rp2040/pio_asm.h, src/platforms/arm/rp2040/pio_gen.h
- add rp2040 platform
- rp2040: fix some issues with fastpin/spi bitbanging (thread safety and accidental use of wrong reg for hival,loval)
- rp2040: support using m0clockless output implementation for >8 strips
- rp2040: switch to custom PIO program that doesn't use sideset avoiding sideset means that we double the max instruction delay, which should increase our timing resolution it also means that there's no longer a separately-licensed block of code included
=> Add rp2040 workarounds to avoid register warnings

src/led_sysdefs.h, src/platforms.h, src/platforms/arm/rp2040/clockless_arm_rp2040.h, src/platforms/arm/rp2040/fastled_arm_rp2040.h, src/platforms/arm/rp2040/fastpin_arm_rp2040.h, src/platforms/arm/rp2040/led_sysdefs_arm_rp2040.h, src/platforms/arm/rp2040/pio_asm.h, src/platforms/arm/rp2040/pio_gen.h
As the title implies, this PR adds some level of support for the RP2040 platform (Raspbetty Pi Pico, etc).  
Currently, I've ported fastpin for software SPI and created a version of clockless output using the platform's PIO feature (programmable state machines that let us create non-blocking output with very little overhead).
Apologies for any problems with this. I'm honestly not much of an embedded dev at all, and so far I've just been testing with a logic analyser. (don't have any spare LEDs at the moment, but that should change soon)
I'm interested in hearing any comments and feedback you may have, as well as the results of testing.
The SDK-provided claims system is used so that resources can used without interfering with other code that behaves well and uses claims.
Resource usage per …
=> Add RP2040 platform (Arduino IDE)

src/platforms/esp/32/clockless_rmt_esp32.cpp
When compiling FastLED with `FASTLED_RMT_SERIAL_DEBUG` unset, I get the failure below. This PR fixes that issue by telling the compiler that espErr is used. Another solution would be to tweak `FASTLED_DEBUG()` when `FASTLED_RMT_SERIAL_DEBUG` is `0` to always compile the debug parameters even if they're removed at link time, but I don't know which linkers you support and I don't want to create any performance regressions. This PR is a no-op apart from silencing the warning.
```
FastLED/src/platforms/esp/32/clockless_rmt_esp32.cpp: In static member function 'static void ESP32RMTController::init(gpio_num_t)':
FastLED/src/platforms/esp/32/clockless_rmt_esp32.cpp:111:15: warning: variable 'espErr' set but not used [-Wunused-but-set-variable]
esp_err_t espErr = ESP_OK;
^ …
```
=> Fix unused variable warning in ESP32RMTController

.github/workflows/build.yml
The build script used for checking all examples with PlatformIO is currently broken. It appears that this is due to the older version of PlatformIO being incompatible with the current platform packages.
This PR updates the packages used in the build script to their latest versions:
| Dependency           | From  | To     |
|----------------------|-------|--------|
| PlatformIO           | 5.03  | 6.1.4  |
| Python               | 3.8   | 3.10   |
| actions/checkout     | v2    | v3     |
| actions/setup-python | v2    | v4     |
| Ubuntu               | 20.04 | latest |
I ran the latest commit (637fac50a28d597e122678340a5cb07a1c766fdc) on my fork [here](https://github.com/dmadison/FastLED/runs/8145649975) and everything appears to be working swimmingly.
=> Fix CI Build Issues

src/noise.cpp
These two functions (`fill_noise8` and `fill_noise16`) take an `int` for the length parameter but use the `fill_noise_raw` functions internally which use a `uint8_t` for the same parameter. This causes an issue where CRGB arrays longer than 255 won't be filled.
To fix, this changes these functions so that they loop through the fills in increments of 255. This preserves the existing behavior and function signature while allowing fills longer than 255.
=> Fix fill_noise functions with lengths > 255

src/platforms/arm/mxrt1062/fastpin_arm_mxrt1062.h
The warnings appear with newer compilers.
=> Fix "narrowing conversion" warnings in fastpin imxrt1062

src/fastpin.h, src/fastspi_types.h
C++17 doesn't support the register keyword. This was already accounted for with the new `#define REGISTER`, however it wasn't applied everywhere. This pull request completes the migration in `fastpin.h` in order to address issue https://github.com/FastLED/FastLED/issues/1457
=> fixes https://github.com/FastLED/FastLED/issues/1457

src/led_sysdefs.h, src/platforms.h, src/platforms/arm/d51/fastpin_arm_d51.h
In similar vein to #662, this adds support for the CAN variant of the M4 Express, which uses a SAM E51.  
For now I've kept it grouped with the D51 since the MCU cores are identical, but the boards have a slightly different pin layout; in particular the built-in NeoPixel has the same Arduino pin number, but is on a different *bit* in the port.
=> Add Adafruit M4 CAN Express

.gitignore, src/controller.h
This can be used by external code to get this information without needing access to the 'input' of the template.
=> Add functions to get the number of lanes from controllers.

src/platforms/arm/sam/fastpin_arm_sam.h
This PR fixes a narrowing conversion warning when using [platformio/toolchain-gccarmnoneeabi](https://registry.platformio.org/tools/platformio/toolchain-gccarmnoneeabi) `>= 1.90201.191206` on [atmelsam](https://registry.platformio.org/platforms/platformio/atmelsam) platforms. This issue is the same as in #1418, but that only fixed the problem on `arm/mxrt1062` platforms; this resolved the issue on `arm/sam` platforms. Perhaps someone should go through the rest of the platform code to fix the same issue on other platforms, but that person isn't me. ;-)
=> Fix narrowing conversion warnings on arm/sam platforms using toolchain-gccarmnoneeabi >= 1.90201.191206

CMakeLists.txt
Enables FastLED as ESP-IDF component support (with Arduino as component)
=> Add FastLED as ESP-IDF component support

src/platforms/esp/32/clockless_rmt_esp32.cpp
The documentation for gpio_matrix_out on esp32c3 is incorrect (https://github.com/espressif/esp-idf/issues/11737), and 0x80 needs to be used instead of 0x100.  Use SIG_GPIO_OUT_IDX, which has the correct value on all platforms.
Fixes #1498
=> Use correct cancel value for gpio_matrix_out on esp32c3

index.html
Changes the "Documentation" navigation links to on the website to point to the generated Doxygen documentation rather than to the Wiki.
=> Change documentation link to Doxygen

README.md
This PR makes some small changes to the README, cleaning up old language and adding contemporary links:
* Removes version number from title, for simplicity and to avoid having to update it on every release
* Removes avr-gcc version warning, which is now 8 years old and presumably unnecessary
* Links "build" badge to build status
* Removed gitter.im badge, as I don't believe this is being used
* Added Reddit badge to FastLED community
* Added Docs badge, linked to Doxygen documentation
* Moved badges below title
* Adds new "Getting Started" section with installation instructions
* Removes folder renaming note for installation, as copying the folder is no longer convention
* Added link to documentation
* Rewrote section emphasizing simplicity and clarity
---
I started to rewrite the …
=> README Docs and Cleanup

src/FastLED.h, src/platforms/arm/k20/octows2811_controller.h, src/platforms/arm/mxrt1062/octows2811_controller.h
This is a convenience in the style of the library already including SmartMatrix, DmxSimple, and DMXSerial. It avoids having to include the header every time FastLED.h is included; this can get tedious for a larger project.
=> Include OctoWS2811.h if USE_OCTOWS2811 is defined

ci/ci-compile, examples/Apa102HD/Apa102HD.ino, src/FastLED.h, src/chipsets.h, src/five_bit_hd_gamma.cpp, src/five_bit_hd_gamma.h
See issue: https://github.com/FastLED/FastLED/issues/1545
Working code. Ready to review.
Here is an example of how it's activated, by using `APA102HD`
```C++
FastLED.addLeds<
APA102HD, APA102_DATA_PIN, APA102_CLOCK_PIN, COLOR_ORDER, DATA_RATE_MHZ(12)
>(leds, NUM_LEDS).setCorrection(TypicalLEDStrip);
```
Here's an example sketch:
```C++
/// @file    Apa102HD.ino
/// @brief   Tests two strips side by side showing off the gamma correction.
/// @example Apa102HD.ino
#include <Arduino.h>
#include <FastLED.h>
#include <assert.h>
#define NUM_LEDS  20
static bool gamma_function_hit = false;
CRGB leds_hd[NUM_LEDS] = {0};  // HD mode implies gamma.
CRGB leds[NUM_LEDS] = {0};     // Software gamma mode.
uint8_t gamma8(uint8_t x) {
return uint8_t((uint16_t(x) * x) >> 8);
}
CRGB gammaCorrect(CRGB c) { …
```
=> Implements "High Bit Depth Gamma Correction Algorithm for APA102/Dotstar LEDs" for APA102 and SK9822 chipsets

README.md, src/chipsets.h, src/five_bit_hd_gamma.cpp, src/five_bit_hd_gamma.h
Real-world testing shows that the ordering between the gamma correction and color correction is wrong.
This cl fixes this and has other tweaks.
This demo demonstrates how the colors are able to hold together, even with conservative power settings (5v @ 5amp power supply). Although some of the frames look white, that is camera sensor saturation and it looks more saturated in the real world.
https://github.com/FastLED/FastLED/assets/6856673/5945fed6-5ea5-437a-bad6-1cb0cce0dd2b
This function made the leds appear washed out and desaturated. This becomes apparent as the power control is applied, which triggers the scaling down of colors.
* APA102HD now longer uses GLOBAL_BRIGHTNESS, as it was causing problems and is redundant with `five_bit_hd_gamma_bitshift()` anyway
* APA102 - no …
=> apply post gamma correction color scaling / brightness control

src/platforms.h
The Adafruit Grand Central Metro M4 (`__SAMD51P20A__`) was in [led_sysdefs.h](https://github.com/FastLED/FastLED/blob/2874c7c8eb13d99ec4ad9a3201054c387d2d8aaa/src/led_sysdefs.h#L34) but missing from [platforms.h](https://github.com/FastLED/FastLED/blob/2874c7c8eb13d99ec4ad9a3201054c387d2d8aaa/src/platforms.h#L34).
This should fix Issues #920 and #1071 and potentially #1531.
=> fix missing check for Adafruit Grand Central Metro M4 in platform.h

src/platforms/arm/renesas/clockless_arm_renesas.h
I found that the timing gave a flicker on WS2812 and WS2818 LED drivers, I think this is due to the T1H timing being >1050ns. The new timing puts the timing at ~800ns for T1H and ~340ns for T0L. This has been tested on genuine UNO R4 WiFi and Minima boards with WS2818B LED strips and WS2812B LED modules
=> Update T1H and T0H timing to fix flicker on UNO R4

src/lib8tion/scale8.h
This function was messing up the APA102HD mode on Teensy 4.1 when brightness == 0.
=> fixes scale16by8 when scale == 0 and FASTLED_SCALE8_FIXED == 1

src/five_bit_hd_gamma.cpp, src/five_bit_hd_gamma.h
It turns out that weak symbol override doesn't work on Teensy 4.1 and platformio. This has been documented and has something to do with the order of linking.
This CL fixes this by using `#define FASTLED_FIVE_BIT_HD_GAMMA_BITSHIFT_FUNCTION_OVERRIDE` and  `#define FASTLED_FIVE_BIT_HD_BITSHIFT_FUNCTION_OVERRIDE` to force extern linking in the FastLED library. This means that if the user doesn't define their own function override then there will be a linker error, rather than silently fail to bind to the strong symbol, which was what was happening before.
=> Fixes apa102HD five bit gamma override on Teensy 4.1 on platformio, others

.github/workflows/build.yml, .gitignore, ci/ci-compile, ci/ci-compile.py, ci/requirements.txt
Reduces the build time by ~75% on a Windows box. Reduces build time by ~65% on github builders.
In the previous iteration, the build artifacts were discarded after every board example.ino. Now the build artifacts are generated just once and then subsequent builds in the board group build the ino file (and its dependencies) and then link the elf file, offering massive speed improvements.
For each board group, the first example.ino build is done under a lock to generate the artifacts, then the rest of the ino files are allowed to be built/linked in parallel.
If this is not done then the github runner will crash without a useful error message. I looked into this a bit and my conclusion is that the cause is an OOM error. Most likely because the massive compilation of the framework and other …
=> reduces the time it takes to build from 12 mins to 2.5 (on Windows 10,12-core)

src/platforms/esp/32/fastspi_esp32.h
I need to override these static/global variables to have a "-1", but the types don't allow it.
Like this:
spiMosi = LED_DATA_PIN;
spiClk = LED_CLOCK_PIN;
spiMiso = -1;
spiCs = -1;
static APA102Controller<LED_DATA_PIN, LED_CLOCK_PIN, BGR,  DATA_RATE_MHZ(10)> c; FastLED.addLeds(&c, _leds, NUM_OF_LEDS);
=> Using correct data types when starting SPI bus for ESP32.

src/noise.cpp
The `fill_...()` functions in `noise.cpp` trigger "warning: stack usage 
might be unbounded [-Wstack-usage=]" if you have -Wstack-usage enabled. There clearly are bound checks in the code, so this warning should be suppressed.
=> Silence -Wstack-usage for noise.cpp

src/platforms/arm/rp2040/led_sysdefs_arm_rp2040.h
=> Don't define cli/sei if defined by Arduino core

src/platforms/arm/rp2040/clockless_arm_rp2040.h, src/platforms/arm/rp2040/led_sysdefs_arm_rp2040.h
Fixes: #1481, #1571
When building for RP2040, at least with -O3 optimizations and the arduino-pico core, the M0 clockless assembly code fails to be assembled for RP2040. This code is only included to be used as a fallback if it fails to claim a DMA channel, which is an undesirable situation to be in anyway.
To keep everyone happy, I've added an option `FASTLED_RP2040_CLOCKLESS_M0_FALLBACK` which is 1 by default but can be set to 0 to disable this fallback and skip compiling `m0clockless.h`. This means the default behaviour remains the same (not breaking backwards compatibility), but gives users the ability to disable the fallback if it's causing them issues.
=> feat: option to disable M0 clockless fallback on RP2040

src/pixeltypes.h
Fixes: https://github.com/FastLED/FastLED/issues/1561
=> Change CRGB constructors from inline to constexpr

src/lib8tion/math8.h, src/lib8tion/scale8.h, src/noise.cpp, src/platforms/avr/clockless_trinket.h
Referring to [GCC Machine Constraints](https://gcc.gnu.org/onlinedocs/gcc/Machine-Constraints.html), the ```a``` constraint restricts GCC to passing inline assembly operands in r16-r23 only.
It seems to me that only a handful of instructions (```MULSU```, ```FMUL```, ```FMULS```, and ```FMULSU```) actually have that constraint, and they are not used by FastLED.
In most cases, it looks to me that the constraint can be relaxed to ```r``` to allow any register, and in several cases to ```d``` to allow r16-r31.
I have not profiled but I suspect that easing the constraint will result in smaller, faster code at least in some circumstances, due to avoiding unnecessary ```MOV``` instructions.  Allowing r24 in particular seems most promising, due to its role in parameter and return value passing …
=> Ease register allocation constraints for AVR

src/platforms/esp/32/fastspi_esp32.h
This pull request aims to resolve issue #1552  by adapting FastLED's SPI handling for the ESP32-S3. The ESP32-S3 diverges from previous ESP32 models by not using named SPI buses (VSPI/HSPI). Instead, it supports flexible pin assignments for SPI communication. In response, this update defaults to "FSPI" for the ESP32-S3, allowing dynamic pin assignment rather than relying on hardcoded pin mappings.
I want to note that while this solution aligns FastLED with the ESP32-S3's SPI flexibility, I'm not entirely certain this is the absolute "best practice" within the broader context of esp-idf and the arduino-espressif library ecosystem. If you know a better way, I'm all ears!
=> #1552: Improve ESP32-S3 SPI Support

src/platforms/esp/32/clockless_rmt_esp32.cpp
This fixes the RMT output for ESP32 when using newer esp32 arduino core (3.x) which uses esp idf 5.x and newer FreeRTOS.
This can most charitably be described as a surgical hack. The right way would be to rewrite using the new RMT interface instead of patching the old one
Sanity tested on ESP32 with default RMT settings
Partially fixes issues #1553, #1605
=> Fix rmt driver for newer versions of idf / freertos

src/noise.cpp, src/noise.h
Partially fixes #1553, #1555 , #1605 
This only fixes the issues in noise.cpp. There are other errors when building for esp32 with the new 3.0 core mostly related to upgrading from espidf 4.x to 5.x which has a new driver model. The RMT and I2S code needs to be updated, but that's a larger change for another day :)
=> Fix ambiguous overload compile errors

tools/paletteknife/index.html, tools/paletteknife/pk2.js
> The original URL for cpt-city now redirects to a mirror of the site, but it only redirects to the base URL rather than the full pathname. This behaviour breaks paletteknife.
> 
> The changes here point paletteknife directly to the mirror, which resolves the problem for me.
Thank you to @sutaburosu for these changes, which were originally submitted here: FastLED/fastled-fastled.github.io#1
=> Update URL for cpt-city

src/platforms/esp/32/clockless_rmt_esp32.cpp
Espressif slightly changed the variable names of their S3 RMT code for idf 5.X. This cl tests the current compiler toolchain to see if it's >= 5.0.0 and if true, uses the correct member variable names.
=> adds support for ESP32S3 RMT for esp-idf 5.X.X

src/platforms/esp/32/clockless_rmt_esp32.cpp, src/platforms/esp/32/clockless_rmt_esp32.h
See issue 1438 (https://github.com/FastLED/FastLED/issues/1438) and others.  FastLED.show() does not return (hangs) very infrequently, sometimes many hours after starting usually while under load.
See https://github.com/davidlmorris/FastLED_Hang_Fix_Demo for a demonstration of this problem (noting that the hang will happen extremely infrequently).
The FastLed RMT driver makes extensive use of interrupts. The comments in the FastLED driver hint at least one per 32 bits of data out. The driver does all the sending in one hit so that even with multiple controllers (as we have in this demo) it is only when the last one is called does it finally does the work. I am uncertain what might happen if only one controller that is not the last one is called. (Something for a future experiment?). On a …
=> clockless_rmt_esp32 FastLED.show() hang fix

ci/requirements.txt
I'm getting build errors with the 6.1.11 version.
Updating to latest in order to silence build errors.
This seems to only happen on my local machine and not the build bot. But better to take care of it now.
=> Update platformio version to 6.1.15

src/chipsets.h, src/fastspi_bitbang.h, src/fastspi_nop.h, src/fastspi_ref.h, src/fastspi_types.h, src/platforms/apollo3/fastspi_apollo3.h, src/platforms/arm/k20/fastspi_arm_k20.h, src/platforms/arm/k66/fastspi_arm_k66.h, src/platforms/arm/kl26/fastspi_arm_kl26.h, src/platforms/arm/mxrt1062/fastspi_arm_mxrt1062.h, src/platforms/arm/nrf51/fastspi_arm_nrf51.h, src/platforms/arm/nrf52/fastspi_arm_nrf52.h, src/platforms/arm/sam/fastspi_arm_sam.h, src/platforms/avr/fastspi_avr.h, src/platforms/esp/32/fastspi_esp32.h, src/platforms/esp/8266/fastspi_esp8266.h, src/platforms/fastspi_ardunio_core.h
Fixes https://github.com/FastLED/FastLED/issues/1653
The compiler fix can be verified by running
`ci/ci-compile --boards esp32-s3-devkitc-1 --examples _bugs/1653_S3_Apa102_Hardware_Pins`
Note that I don't actually know if this works or not, I just fixed the compiler errors.
=> fixes 1653 compiler error for Apa102 hardware spi pins on ESP32-S3

src/led_sysdefs.h, src/namespace.h, src/platforms/esp/32/clockless_rmt_esp32.h, src/platforms/esp/32/idf4_clockless_rmt_esp32.h, src/platforms/esp/32/idf4_rmt.cpp, src/platforms/esp/32/idf4_rmt.h, src/platforms/esp/32/idf5_clockless_rmt_esp32.h
This is needed in preparation for a new RMT driver for the esp-idf 5.x platform.
There was an issue with having to include "FastLED.h" for the namespace stuff. So namespace.h has been created so that cpp files can use a more minimal inclusion system.
=> split the esp32-idf 4.x vs 5.x rmt driver. 5.x just redirects to 4.x

src/noise.h, src/simplex.cpp
Simplex noise has some benefits over classical (or improved) Perlin noise. It generally has fewer artifacts than previous versions. It still has artifacts, just a lot less noticeable. It is also possible to easily extend the algorithm to higher dimensions without exponentially increasing the computational requirements. One practical advantage is that this implementation also includes a 4D version while the other noise functions only implement 1D, 2D and 3D versions.
The implementation has been optimized for 32-bit microcontrollers. I've tried to keep all calculations in 32-bit integers, only going to 64-bit when really necessary.
The API is a bit different because I converted to fixed-point separately. I also didn't care about possible benefits for microcontrollers for a 16.16 fixed point …
=> Add simplex noise [revisit this PR in 2022]

src/platforms/arm/common/m0clockless.h, src/platforms/arm/rp2040/clockless_arm_rp2040.h
- RP2350 features three PIO instances!
- fix double define for SysTick
=> correct RP2350 PIO count / fix double define SysTick

src/platforms/esp/32/idf4_clockless_rmt_esp32.h, src/platforms/esp/32/idf4_rmt.cpp, src/platforms/esp/32/idf4_rmt.h, src/platforms/esp/32/led_strip/led_strip_rmt.h
Some things were being defined twice with the RMT driver and the led_strip component. In this case I've isolated the old RMT component and all of it's esp stuff to the cpp file instead of a header file.
Now a proxy object with a pointer-to-implementation is used to access the compiled RMT code without exposing headers to other parts of the rmt driver base.
=> allow rmt led strip component to be compiled in fastled

src/simplex.cpp
`1 << 27` overflows on AVR because the `int` 1 is only 16 bits.
```cpp
/home/runner/Arduino/libraries/FastLED/src/simplex.cpp: In function 'uint16_t snoise16(uint32_t, uint32_t)':
/home/runner/Arduino/libraries/FastLED/src/simplex.cpp:160:25: warning: left shift count >= width of type [-Wshift-count-overflow]
int32_t t0 = ((1 << 27) - x0*x0 - y0*y0) >> 12; // .16
^~
/home/runner/Arduino/libraries/FastLED/src/simplex.cpp:167:25: warning: left shift count >= width of type [-Wshift-count-overflow]
int32_t t1 = ((1 << 27) - x1*x1 - y1*y1) >> 12; // .16
^~
/home/runner/Arduino/libraries/FastLED/src/simplex.cpp:174:25: warning: left shift count >= width of type [-Wshift-count-overflow]
int32_t t2 = ((1 << 27) - x2*x2 - y2*y2) >> 12; // .16
^~
```
=> Fix shift count overflow on AVR in simplex snoise16

.github/workflows/build_rp2040_earle.yml, ci/boards/rpipico.json, ci/ci-compile.py
Instead of just compiling for `nanorp2040connect` which by-default uses the ArduinoCore-mbed, explicitly adds `rpipico` to the build as Rasberry Pi Pico (Arduino-Pico core by Earle Phihower).
=> Add RP2040 Arduino-Pico build

examples/Apa102HD/Apa102HD.ino, src/platforms/arm/nrf52/fastpin_arm_nrf52.h
Turn 20 pages of compiler error messages into one line on the nrf sense boards.
This pattern should probably be copied everywhere to reduce compiler spew.
=> Make NRF sense work

.github/workflows/build_nano_every.yml, src/platforms/avr/fastpin_avr.h, src/platforms/avr/fastpin_avr_atmega4809.h, src/platforms/avr/fastpin_avr_nano_every.h
Changes:
1. Complete removal of `ARDUINO_AVR_NANO_EVERY` conditionals from `fastpin_avr.h` to avoid unintentional overwriting pin definition. Arduino Nano Every is subset of ATmega4809 .
2. Extract file `fastpin_avr_atmega4809.h` from `fastpin_avr.h`
More details on:
- https://github.com/FastLED/FastLED/pull/1719#issuecomment-2359697145
=> Further clean up after PR 1719 for Nano Every

src/chipsets.h
C/++11 does not support calling static_assert with no error message. This PR adds it. 
In all honest I did not completely understand the functioning so I just copied the message from above. 
Please feel free to edit it as deemed necessary :)
Thanks for all the awesome work in FastLED <3
EDIT: This fixes #1734.
=> Fix static_assert call on C++11 (fixes #1734)

src/chipsets.h
Controllers for WS211X chipsets are defined twice in `chipdset.h`, within a `#ifdef ... #else ...` structure.
The default color order is different for both definitions.
Set to `GRB` for all of them.
=> default order GRB for WS211X controllers in chipset.h

src/third_party/arduinojson/json.h
Fixes #1757 for GCC >=5, but an alternative solution needs to be found for older GCC (e.g. Arduino Due, which is still stuck on GCC 4.8).
=> Use #pragma push_macro(ARDUINO) in arduinojson wrapper

src/pixelset.h
This PR includes two fixes when working with `CPixelView` when reverse direction is set (`dir == -1`).
For `operator()`, it now returns a new CPixelView with the correct `dir` value, respecting the `dir` value of the original `CPixelView`. It hides the internal `led` array from the user, so they do not need to know whether the original `CPixelView` is in forwards or reverse order.
For `CPixelView::fill_rainbow`, it now behaves similar to `CPixelView::fill_gradient`, `CPixelView::fill_gradient_RGB`, `CPixelView::nblend`, and other methods. It swaps the start and end colours when `dir == -1`. Again, this allows a reversed `CPixelView` to be treated the same as a physically reversed strip of LEDs, so the user does not need to know any details of the internal `led` array and `dir` value to …
=> Fix fill_rainbow and operator() for CPixelView with reverse direction

src/fx/fx.h, src/rgbw.cpp, src/xymap.h
This fixes several compiler warnings by casting unused parameters into the void where they belong.
=> Fix unused parameter compiler warnings

examples/Fire2012WithPalette/Fire2012WithPalette.ino, examples/FxEngine/FxEngine.ino, examples/Overclock/Overclock.ino, examples/PinMode/PinMode.ino
This fixes several compile errors that have cropped up in example sketches.
The fixes to `FxEngine.ino` and `Overclock.ino` are due to the changes from commit be60207.
Note that the order of operations shift in `Fire2012WithPalette.ino` was made because the WASM compiler does not automatically insert function prototypes like the Arduino IDE does and so it was erroring out. Moving the custom function above the loop resolves this issue (and in fact this keeping of custom functions above the loop can be seen in FastLED's existing example sketches such as `SmartMatrix.ino`).
On the topic of the WASM compile test, `Esp32Rmt51.ino` should be excluded as its platform definition lacks `FASTLED_RMT5` and thus this is an invalid sketch for WASM. Additionally `SmartMatrix.ino` should be excluded as …
=> Fix compile errors in examples

.github/workflows/docs.yml
This makes it possible to generate the documentation without needing to push a new release, in case documentation is updated between releases, documentation software is updated, or if the documentation action fails for any reason.
=> Add workflow dispatch to docs action

src/lib8tion/brightness_bitshifter.h
Checking the same condition twice clearly isn't correct. This changes the early return code for brightness_bitshifter16 to look identical to brightness_bitshifter8.
I noticed this when [porting this code to Rust](https://github.com/smart-leds-rs/apa102-spi-rs/pull/15) and running clippy on it.
=> fix early return check for brightness_bitshifter16

src/lib8tion/scale8.h
`i * (1 + scale)` would overflow before the `>> 8` if it was stored in a uint16_t. Some implicit type conversion must be going on to make this work, but it's unclear if that implicit type conversion would reliably work on all platforms. The `1` literal may be casting `1 + scale` to an `unsigned int`, which on most platforms is 32 bits, but the C++ standard allows it to be 16 bits.
Fixes https://github.com/FastLED/FastLED/issues/1821
=> scale16by8: explicitly use uint32_t for intermediate computations

README.md, examples/Overclock/Overclock.ino, release_notes.md
Fix the overclock examples. The define should be FASTLED_LED_OVERCLOCK
=> Fix overclock examples

src/platforms/esp/8266/clockless_block_esp8266.h
MIN is also defined in fl/math_macros.h, avoid the compiler warning.
=> esp8266 clockless only define MIN if not already defined

tests/test_brightness_bitshifter.cpp
using fixed data in addition to the existing tests using randomly generated data.
I didn't realize these functions had some tests already before writing these. I figure they're helpful to add anyway; they helped me understand how these functions work.
=> add more tests for brightness_bitshifter functions

CONTRIBUTING.md
This is already ignored by .gitignore.
=> README.md: use tests/.build for CMake build directory

src/platforms/arm/d21/clockless_arm_d21.h
Thanks to [@apozharski](https://github.com/apozharski) for doing the hard work of isolating the bug.  Since I ran into this, I went ahead and submitted this PR.
I put the zero length check at the lowest level possible so it would catch all code paths.
=> Fix #1101 - check for num_leds == 0 and skip output routine

src/FastLED.cpp, src/chipsets.h, src/cled_controller.h, src/cpixel_ledcontroller.h, src/platforms/arm/k20/clockless_objectfled.h, src/platforms/esp/32/rmt_5/idf5_clockless_rmt_esp32.h
These changes make WS2816 work with the Teensy4's ObjectFLED controller and ESP32S3's IDF5 RMT controller.  They also fix CFastLED::showColor.
FWIW, my ESP32 board is a Seeed XAIO ESP32S3.  That seems to be the default in `platformio.ini`, so I'm not the only one using it.  The examples all use pin 3, and when I run them, the LED signals appears on the pin labeled A2.  The parallel examples use pins 1 and 3, and those come out on A0 and A2.  This seems to be consistent with Arduino's pin assignments, but it contradicts the silkscreen and [Seeed's own documentation](https://wiki.seeedstudio.com/xiao_esp32s3_getting_started/).  It's also consistent across FastLED/PlatformIO and FastLED/Arduino, and not dependent on using WS2816, so I think it's right.  It's just disconcerting.
=> Fix WS2816 on ObjectFLED and ESP32S3

src/chipsets.h, src/cpixel_ledcontroller.h, src/platforms/arm/k20/clockless_objectfled.h, src/platforms/esp/32/rmt_5/idf5_clockless_rmt_esp32.h
Working on the WS2816 support, I learned that some controllers care about the order in which their beginShowLeds, showPixels, and endShowLeds methods are called.  RGBWEmulatedController was not calling them in the correct order.  So I side-ported some code from WS2816 to fix RGBWEmu.
(Yes, those two controllers already have RGBW support.  But others probably have the same order dependency. ESP32 and Teensy4 are the test boards I have available.)
=> Make RGBWEmulated work with ObjectFLED, ESP3D RMT5, and other controllers

src/platforms/avr/led_sysdefs_avr.h
`LIB8_ATTINY` was not being defined, which led to the invalid opcode errors.
=> Fix ATtiny4313/13 builds

.github/workflows/build.yml, .github/workflows/build_esp32dev_idf3.3.yml, ci/ci/boards.py, src/fx/1d/fire2012.h
add a test build task to avoid future ESP32 compile problems for projects based on  ESP-IDF 3.3 LTS
=> Enable test compiles for ESP32 with ESP-IDF 3.3 LTS

src/led_sysdefs.h, src/platforms.h, src/platforms/arm/giga/fastpin_arm_giga.h
Additional platform identifier define ARDUINO_GIGA added. Fixes issues with non recognizable platform when building with Arduino IDE
=> Additional platform identifier define added for giga r1

src/fx/2d/noisepalette.cpp, src/fx/2d/noisepalette.h
compiling the library using latest EDP IDF V5.4 produce compiler warning as error [-Werror=mismatched-new-delete] 
this is due to allocating  using 
new uint8_t[width * height]  ( using [] ) 
while deleter is not using [] operators  in scoped_ptr  
fix : using scoped_array instead
=> fixing ESP IDF V 5.4 compiler error [-Werror=mismatched-new-delete]

src/fl/inplacenew.h
Closes: #1909
This adds a new define check using `FASTLED_HAS_NEW` to prevent redefinition of `operator new()` on AVR as that is also defined by the `ArduinoSTL` library.
=> 1909: Add preproccesor check to prevent redefinition of new()

src/colorutils.cpp, src/colorutils.h
nblend take two buffer: the first (`existing`) that is used as _input/output_ and a second `overlay` that as the name imply is overlayed on top of the first one by `amountOfOverlay` amount
`overlay` buffer data is never modified, mark the signature as "mutable pointer to const data"
=> nblend overlay data is const, mark it as such

CMakeLists.txt
added 'esp_lcd' in the CMake since its needed and not included by default in ESP32-S3 compile using IDF v5.4
=> Updates component dependencies in CMake configuration for esp-idf v5.4 ESP32(S3) needed dependency 

src/platforms/esp/32/rmt_5/strip_rmt.cpp
Didn't dig much deeper, but it seems, that this makes at least for my setup a difference (ESP32-WROVER-E).
Sadly the Clockless SPI doesn't work on my ESP32 version. Was not able to find out why this is not possible on this board, but will dig deeper on the exact reason.
Thanks a lot for your great work!
=> fix: use dma if enabled

.github/workflows/build_wasm_compilers.yml, ci/ci/boards.py, platformio.ini
This should fix the ESP32C2 build action by updating the `platformio.ini` file with an updated SDK definition. This definition is required to avoid the `**** missing SConscript file ‘/home/cw/.platformio/packages/framework-arduinoespressif32-libs/esp32c2/pioarduino-build.py’*` error, per [this discussion](https://community.platformio.org/t/use-of-arduino-esp32-in-platformio/45382/22).
It also fixes some improper indentation in `build_wasm_compilers.yml` which was causing errors when the action tried to start.
=> Fix ESP32C2 build action

ci/ci-compile.py, ci/ci/boards.py, ci/ci/concurrent_run.py, ci/ci/create_build_dir.py, platformio.ini
Updates the platform address and custom_sdkconfig parameter passing functions in order to correct compilation for the ESP32C2.
Thanks to the Github Actions CI now working to target PR changes, I have confirmed that the fixes included in this PR lead to successful build for the ESP32C2. Thank you again for swiftly fixing that!
=> ESP32C2 Compile Fix

src/platforms/arm/stm32/fastpin_arm_stm32.h
This PR fixes the STM32F1 pin mapping issue reported in #744, which prevented FastLED from working on Blue Pill and other STM32F1 boards.
The issue was that FastLED's pin definition selection logic was too restrictive, causing most STM32F1 boards to fall back to broken legacy pin definitions that use arbitrary Arduino pin numbers instead of proper STM32 pin names like `PA7`, `PB5`, etc.
Users experienced:
- Compilation errors when using STM32 pin names like `PA7`
- No LED activity even when compilation succeeded
- Need for manual workarounds or file replacements
Expanded the `USE_NEW_STM32_PIN_DEFINITIONS` condition in `src/platforms/arm/stm32/fastpin_arm_stm32.h` to include all common STM32F1 board definitions:
```cpp
// Before (restrictive)
#if defined(ARDUINO_BLUEPILL_F103C8) || …
```
=> Fix STM32F1 pin mapping issue (#744)

examples/Audio/advanced/advanced.h
If matrix WIDTH < (2 x NUM_BINS) , then `int barWidth =  WIDTH / NUM_BANDS` = 1 (or even 0). 
So `barWidth - 1` = 0,
So the loop at line 198 ` for (int x = 0; x < barWidth - 1; x++)`  never executes.
=> Fix Audio advanced.h drawSpectrumBars()
