FastLED/FastLED

led_sysdefs.h
platforms.h
platforms/arm/d21/fastpin_arm_d21.h

not much changes, just add defined(__SAMD21E18A__) a couple places and a board definition.
plz ask if you have any Qs
thankx! :)

Add support for __SAMD21E18A__ (Adafruit Gemma M0) + typo

---

examples/Multiple/ArrayOfLedArrays/ArrayOfLedArrays.ino

Typo in comment, said four strips on three pins

ArrayOfLedArrays.ino

---

platforms/arm/k20/fastspi_arm_k20.h

SPI fifo byte push and TCF bit clear done using interrupts disable to prevent race condition between
writeByte* routines and waitFully. In additional, waitFully only disables interrupts briefly while waiting for the fifo to empty to allow interrupts to be serviced.

Race condition fix for ARMHardwareSPIOutput::waitFully on Teensy 3.1/2

---

platforms/arm/d21/fastpin_arm_d21.h

Adding Trinket M0 and Gemma M0 support - these little boards <3 FastLED but needed their pins defined :)

fixed gemma and trinket m0 support - tested all pins on both boards

---

library.json

https://github.com/FastLED/FastLED/pull/539

Don't archive library with @PlatformIO Builder

---

FastLED.h
README.md
chipsets.h
examples/RGBCalibrate/RGBCalibrate.ino
keywords.txt

LPD6803 - SPI based chpiset.
Chip CMODE pin must be set to 1 (inside oscillator mode).

Add support LPD6803

---

platforms/avr/fastpin_avr.h
platforms/avr/fastspi_avr.h

SPI mode is not tested. Its tested with WS2812 etc

added support for AVR atmega328pb

---

chipsets.h

Thanks to @cmsavage for a heads up. I was able to reproduce the issue and applied the suggested fix. With the fix I don't see overflows happening anymore. Fixes #656.
/cc @focalintent

Update global brightness math to fix overflows

---

chipsets.h
examples/Pintest/Pintest.ino
fastspi.h
fastspi_bitbang.h
fastspi_nop.h
fastspi_ref.h
led_sysdefs.h
platforms.h
platforms/arm/k20/fastspi_arm_k20.h
platforms/arm/k66/fastspi_arm_k66.h
platforms/arm/kl26/fastspi_arm_kl26.h
platforms/arm/mxrt1062/block_clockless_arm_mxrt1062.h
platforms/arm/mxrt1062/clockless_arm_mxrt1062.h
platforms/arm/mxrt1062/fastled_arm_mxrt1062.h
platforms/arm/mxrt1062/fastpin_arm_mxrt1062.h
platforms/arm/mxrt1062/fastspi_arm_mxrt1062.h
platforms/arm/mxrt1062/led_sysdefs_arm_mxrt1062.h
platforms/arm/nrf51/fastspi_arm_nrf51.h
platforms/arm/nrf52/fastspi_arm_nrf52.h
platforms/arm/sam/fastspi_arm_sam.h
platforms/avr/fastspi_avr.h
release_notes.md

Filing as a pull request to keep the record around of it

Teensy 4 support!

---

examples/Multiple/MultiArrays/MultiArrays.ino

Correction so that the Blue LEDs are properly blacked out

Fix typos causing blue LEDs to not clear

---

examples/Blink/Blink.ino
examples/FirstLight/FirstLight.ino
examples/RGBCalibrate/RGBCalibrate.ino

Make examples consistent and document the likely non-RGB types

---

power_mgt.h

```set_max_power_indicator_LED``` has not been depracated and is still use in ```power_mgt.cpp```

wrong comment location

---

platforms/avr/clockless_trinket.h

Fix small typo in comment

---

platforms/esp/32/clockless_i2s_esp32.h

I added this wait to the RMT driver and it seemed to help.

Added an enforced minimum wait of 50 microseconds between calls to show

---

platforms/arm/d21/fastpin_arm_d21.h

add qt py support!

---

src/platforms/arm/mxrt1062/block_clockless_arm_mxrt1062.h

I accidentally left in a conflict that got merged in #997. There were also `}` missing for a function. This fixes that.

fix rebase artifact

---

src/platforms/esp/32/clockless_rmt_esp32.cpp

Remove an unused variable 'stuff_to_do'

---

code_of_conduct.md

Dan and I had been planning to add this Code of Conduct; finally doing it now.

Adding Code of Conduct from https://www.contributor-covenant.org/

---

src/platforms/esp/32/clockless_rmt_esp32.cpp

see also issue #1329
replace PR #1330 because #1330 contains extra files not relevant for the merge

avoid 200ms flicker every ~17.9 seconds with RMT driver

---

src/fastspi.h
src/platforms/esp/8266/fastled_esp8266.h
src/platforms/esp/8266/fastspi_esp8266.h

Implementation of SPI for ESP8266

ESP8266 SPI

---

examples/SmartMatrix/SmartMatrix.ino

My very first pull request, I hope this is the way to do.

Clarifies the need for SmartMatrix library and scope limited to Teensy boards

---

src/platforms/esp/32/fastspi_esp32.h

Add FSPI bus to support ESP32S2.
Add spi.h include for easier compilation.
Make ledSPI static to avoid multiple instantiations.

Add esp32s2 spi (FSPI) support, some code usability improvements

---

src/fastspi.h

Ref: https://forum.pjrc.com/threads/70671-Teensy-4-1-with-FastLed-No-Hardware-SPI
Companion PR: https://github.com/PaulStoffregen/FastLED/pull/1
Fixes #1410

Fix Teensy 4 SPI1_CLOCK

---

src/colorutils.h

Change operator==() and operator!=() in colorutils.h to use references

---

src/pixeltypes.h

Add CRGB::operator uint32_t()

---

src/pixeltypes.h

Make CRGB::operator bool() explicit

---

src/platforms/avr/fastpin_avr.h
src/platforms/avr/led_sysdefs_avr.h

add support for ATtiny48/88

---

release_notes.md
src/colorpalettes.cpp

Spelling fix - Particle Photon (instead of Partical), spotted by Chris Kirkman in Reddit group.

Update release_notes.md (spelling fix)

---

src/led_sysdefs.h
src/platforms.h
src/platforms/arm/renesas/clockless_arm_renesas.h
src/platforms/arm/renesas/fastled_arm_renesas.h
src/platforms/arm/renesas/fastpin_arm_renesas.h
src/platforms/arm/renesas/led_sysdef_arm_renesas.h

Tested on Neopixel-like (clockless)

renesas: initial porting for UNO R4

---

README.md

Make a start (however miniscule) on providing information about porting FastLED to new platforms.
Fixes: #1557

 [README.md] Add a pointer to PORTING.md

---

src/lib8tion.h

I update the template class named as q to qfx which might resolve the problem as re-declaration of q of different kind of type.
This PR will might resolve issue #1485.

update the class q name as class qfx in lib8tion.h

---

.gitignore

Ignore some cruft my build environment tried to foist upon this project.

Add a couple more things for git to ignore

---

src/colorutils.h

Fixes https://github.com/FastLED/FastLED/issues/1658

Fill LED range with smooth HSV gradient between two colors

---

src/platforms/esp/32/clockless_rmt_esp32.cpp

Fixes C6 so that it now compiles. Correct behavior has not been established yet.
This will fix compiling for WS2812. I noticed that the APA102 stuff still does not compile but that will be addressed later.

Fix esp32 c6

---

src/platforms/arm/d21/fastpin_arm_d21.h

Adding the Adafruit Pixel Trinkey M0 (https://www.adafruit.com/product/5953)

Adding Adafruit Pixel Trinkey M0

---

.github/workflows/buiild_adafruit_feather_nrf52840_sense.yml
ci/ci-compile.py
src/platforms/arm/nrf52/fastpin_arm_nrf52_variants.h

fixes https://github.com/FastLED/FastLED/issues/1647

Nrf feather sense support for WS2812

---

src/bitswap.cpp
src/eorder.h
src/pixeltypes.h
src/platforms/esp/32/clock_cycles.h
src/platforms/esp/32/clockless_block_esp32.h
src/platforms/esp/32/fastled_esp32.h
src/platforms/esp/32/idf4_rmt.cpp
src/transpose8x1_noinline.cpp
src/transpose8x1_noinline.h

Fixes compiler error: https://github.com/FastLED/FastLED/issues/1572

ESPC2 Experimental fix

---

src/fastspi.h
src/led_sysdefs.h
src/platforms.h
src/platforms/stub/clockless_stub.h
src/platforms/stub/fastled_stub.h
src/platforms/stub/fastspi_stub.h
src/platforms/stub/led_sysdefs_stub.cpp
src/platforms/stub/led_sysdefs_stub.h

Yes we need x86 stubs. I wanted to do this myself but found out that someone had already done it.

manually merged in stub from https://github.com/FastLED/FastLED/pull/1366

---

src/platforms/avr/clockless_trinket.h

From 
https://github.com/FastLED/FastLED/pull/1268

manually merge changes from https://github.com/FastLED/FastLED/compare/master...ben-xo:FastLED:feature/avr-clockless-trinket-interrupts

---

src/colorutils.cpp
src/colorutils.h

courtesy of https://github.com/sutaburosu for the code solution.
See also.
https://github.com/FastLED/FastLED/pull/1659

Add ColorFromPaletteExtended function for higher precision

---

src/simplex.cpp

Optimizations lifted from https://github.com/aykevl

improved simplex noise

---

src/colorutils.cpp
src/colorutils.h

https://github.com/generalelectrix
https://github.com/sutaburosu

adds extended color pallette for 256

---

dev/dev.ino
src/controller.h
src/platforms/esp/32/idf4_clockless_rmt_esp32.h
src/platforms/esp/32/idf4_rmt.cpp
src/platforms/esp/32/idf4_rmt.h
src/platforms/esp/32/idf4_rmt_impl.h
src/rgb_2_rgbw.cpp
src/rgb_2_rgbw.h

adds working RGBW mode for ESP32 RMT driver behind experimental flags
adds dev.ino demo

Adds experimental RGBW support for ESP32 WS2812 RGBW

---

src/FastLED.h
src/bitswap.h
src/chipsets.h
src/controller.h
src/fastled_delay.h
src/fastspi_bitbang.h
src/fastspi_types.h
src/force_inline.h
src/pixelset.h
src/platforms/arm/d21/fastpin_arm_d21.h
src/platforms/arm/d51/fastpin_arm_d51.h
src/platforms/arm/k20/fastpin_arm_k20.h
src/platforms/arm/k66/fastpin_arm_k66.h
src/platforms/arm/kl26/fastpin_arm_kl26.h
src/platforms/arm/mxrt1062/fastpin_arm_mxrt1062.h
src/platforms/arm/nrf51/fastpin_arm_nrf51.h
src/platforms/arm/nrf52/led_sysdefs_arm_nrf52.h
src/platforms/arm/sam/fastpin_arm_sam.h
src/platforms/arm/stm32/fastpin_arm_stm32.h
src/platforms/avr/clockless_trinket.h
src/platforms/esp/32/clockless_block_esp32.h
src/platforms/esp/32/idf4_rmt_impl.cpp
src/rgb_2_rgbw.h

`__attribute__((always_inline)) inline` -> `FASTLED_FORCE_INLINE` everywhere

impliments force inline

---

src/FastLED.h

cpp check says that the switch statement can return void even though it's got a defined return type. I've refactored the addLed(...) code for clocked chipsets to handle this case. This will fix the CPP check issue as well as centralizing clocked chipset mappings so it's only done in one place instead of 3.

Refactor addLed switch statement to use template specialization

---

README.md
release_notes.md

adding credits to the merged PR https://github.com/FastLED/FastLED/pull/1292

Update Release Notes for PR 1292 ( ATtiny 0/1 )

---

.vscode/tasks.json
src/five_bit_hd_gamma.cpp
src/five_bit_hd_gamma.h
tests/test_apa102_hd.cpp

Apa102 global

---

src/five_bit_hd_gamma.cpp
tests/CMakeLists.txt
tests/test_apa102_hd.cpp

add tests for APA102HD algorithm

---

src/platforms/esp/32/rmt_4/idf4_rmt_impl.h

as discussed and agreed in #1856

remove IRAM_ATTR from showPixel 

---

src/hsv2rgb.cpp

See this thread comment for the source of this solution:
https://github.com/FastLED/FastLED/pull/943#issuecomment-845751972

Fixes jumping red pixel - see https://github.com/FastLED/FastLED/pull/943

---

README.md

This has finally been released in a published crate. Thanks for your comment moving the PR along; it finally got a reviewer to merge my PRs.

README: update link for Rust port of the APA102 algorithm

---

src/platforms/wasm/active_strip_data.cpp
src/platforms/wasm/exports.h
src/platforms/wasm/js.cpp

---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/FastLED/FastLED/pull/1928?shareId=dd5f2e7f-3243-45eb-aa8b-c562b322d3ee).

Remove embind usage and replace with pure C interface

---

.github/workflows/build_wasm_compilers.yml
.github/workflows/docs2.yml

Fixes incorrect indentation that is causing these actions to fail.

Fix build_wasm_compilers.yml and docs2.yml
